services:
  users-service:
    build: .
    container_name: microservice
    ports:
      - "3001:3001"
    depends_on:
      - postgres-users
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres-users:5432/usersDB?schema=public
      POSTGRES_HOST: postgres-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersDB
      DB_PORT: 5432
    command: ["./entrypoint.sh"]
    networks:
      - backend-network

  postgres-users:
    image: postgres:15
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-users:5432/usersDB?schema=public
      POSTGRES_HOST: postgres-users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersDB
      DB_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata_users:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
